### ISSUE TITLE
Prepare for release - are the dev_dependencies required?

### ISSUE THREAD

**Issue by gjwgit** [anusii/import_order_lint#4]
Are the following dev dependencies required for the package?

```
dev_dependencies:
  build_runner: ^2.4.8
  # Ensures Dart's built-in testing framework is included
  test: ^1.21.0
```
